embedding_size: [1024]
n_layers: [3]
reg_weight: 0.0001
learning_rate: [1e-4,5e-5,1e-5]
train_batch_size: [512,1024,2048]
temperature: [0.2,0.1]

hyper_parameters: ["n_layers", "temperature","learning_rate","embedding_size","train_batch_size"]

